services:
  - type: web
    name: des-demo
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: des
      - key: ENGINE
        value: openai
      - key: DOTLOOP_CLIENT_ID
        sync: false
      - key: DOTLOOP_CLIENT_SECRET
        sync: false
      - key: DOTLOOP_API_TOKEN
        sync: false
      - key: DOTLOOP_REFRESH_TOKEN
        sync: false
      - key: DOTLOOP_PROFILE_ID
        sync: false
      - key: DOCUSIGN_CLIENT_ID
        sync: false
      - key: DOCUSIGN_CLIENT_SECRET
        sync: false
      - key: DOCUSIGN_ACCOUNT_ID
        sync: false
      - key: DOCUSIGN_USER_ID
        sync: false
      - key: DOCUSIGN_AUTH_SERVER
        value: account-d.docusign.com
      - key: DOCUSIGN_BASE_URL
        value: https://demo.docusign.net/restapi
    healthCheckPath: /api/documents
